- hosts: k8s
  gather_facts: False
  tasks:
    - name: Add k8s repositories
      yum_repository:
        name: Kubernetes
        description: Kubernetes Repositories
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgcheck: 1
        enabled: 0
        repo_gpgcheck: 1
        gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

    - name: Add aliyun k8s repositories
      yum_repository:
        name: KubernetesAliyun
        file: aliyun_k8s
        description: Kubernetes Repositories
        baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
        gpgcheck: 0
        enabled: 1
