- hosts: k8s
  gather_facts: False
  tasks:
    - name: Add aliyun k8s repositories
      yum_repository:
        name: KubernetesAliyun
        file: aliyun_k8s
        description: Kubernetes Repositories
        baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
        gpgcheck: 0
        enabled: 1
