- hosts: k8s
  gather_facts: False
  tasks:
    - name: install k8s
      yum:
        name:
          - kubelet-1.19.16
          - kubeadm-1.19.16
          - kubectl-1.19.16
        state: present
