- hosts: k8s
  gather_facts: False

# set hostname
#
- name: add repo
  import_playbook: add_repo.yml 

- name: add hosts
  import_playbook: add_hosts.yml

- name: set hostname
  import_playbook: set_hostname.yml

- name: install docker and k8s
  import_playbook: install_docker_k8s.yml 

- name: start service
  import_playbook: start_service.yml

